project:
  type: website

website:
  #title: 
  favicon: "LOGO_orange.png"
  navbar:
    logo: 'N_EAM.png'
    logo-alt: 'NEAM'
    left:
      - href: research
        text: Research
      - href: team
        text: Team
      - href: publications
        text: Publications
      - href: blog
        text: Blog
      - href: contact
        text: Contact
    #right:

format:
  html:
    theme: lux
    linkcolor: green