---
title: "Publications"
---

## Preprints

K. Studeničová, A. Morales Gregorio, Antonio Lozano, Xing Chen, Cristina Soto Sanchez, Eduardo Fernandez, Paolo Papale, Karolína Korvasová (2026) Cell-type-specific coupling of single-unit spikes and cortical ripples in macaque and human V1, bioRxiv, [doi: https://doi.org/10.64898/2026.07.02.736041](https://www.biorxiv.org/content/10.64898/2026.07.02.736041v1)

E. L. Marosi, K.Korvasová, F Ludwig, H. Kaneko, L. Sosulina, T. Tetzlaff, S. Remy, S.. Mikulovic (2021, major update in 2026 including new data) Persistent firing neurons in the medial septum drive arousal and locomotion, bioRxiv, [doi: 10.1101/2021.04.23.441122](https://doi.org/10.1101/2021.04.23.441122)

A. Morales Gregorio, A. C. Kurth, K. Korvasová (2026) Geometric developmental principles for the emergence if brain-like weighted and directed neuronal networks, arXiv, [doi: 10.48550/arXiv.2601.05021](https://doi.org/10.48550/arXiv.2601.05021)

## Peer-reviewed articles

Morales-Gregorio A., Kurth A. C., Ito J., Kleinjohann A., Barthélemy F., Brochier T., Grün S., van Albada S. J. (2024) Neural manifolds in V1 change with top-down signals from V4 targeting the foveal region. Cell Reports [doi: 10.1016/j.celrep.2024.114371](https://linkinghub.elsevier.com/retrieve/pii/S2211124724006995)

Senk J., Korvasová K., Schuecker J., Hagen E., Tetzlaff T., Diesmann M., and Helias
M. (2020) Conditions for wave trains in spiking neural networks, Physical Review
Research 2, [doi: 10.1103/PhysRevResearch.2.023174](https://doi.org/10.1103/PhysRevResearch.2.023174)


Diekmann, O., Korvasová, K. (2016) Linearization of solution operators for
state-dependent delay equations: A simple example, Discrete & Continuous
Dynamical Systems - A 36, [doi: 10.3934/dcds.2016.36.137](https://doi.org/10.3934/dcds.2016.36.137)

Korvasová, K., Gaffney, E. A., Maini, P. K., Ferreira, M. A., & Klika, V. (2015).
Investigating the Turing conditions for diffusion-driven instability in the presence
of a binding immobile substrate. Journal of Theoretical Biology, 367, [doi: 10.1016/j.jtbi.2014.11.024](https://doi.org/10.1016/j.jtbi.2014.11.024)

Diekmann, O., Korvasová, K. (2013) A didactical note on the advantage of using two
parameters in Hopf bifurcation studies, Journal of Biological Dynamics 7, [doi: 10.1080/17513758.2012.760758](https://doi.org/10.1080/17513758.2012.760758)

Penington, C.J., Korvasová, K., Hughes, B.D., Landman, K.A. (2012) Collective
motion of dimers, Physical Review E 86, [doi: 10.1103/PhysRevE.86.051909](https://doi.org/10.1103/PhysRevE.86.051909)



## Popular science articles

Brejcha J., Korvasová K., Patrnosti mimikry (Part 1), [Vesmír 102, 484, 2023/9](https://vesmir.cz/cz/casopis/archiv-casopisu/2023/cislo-9/patrnosti-mimikry.html)

Brejcha J., Korvasová K., Patrnosti mimikry (Part 2), [Vesmír 102, 577, 2023/10](https://vesmir.cz/cz/casopis/archiv-casopisu/2023/cislo-10/-2.html)

